project:
  type: website
  output-dir: docs

website:
  title: "Middlebury College CSCI 0451 Blog - Col McDermott"
  navbar:
    background: "black"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Col-McDermott

format:
  html:
    title-block-banner: img/landscape.png
    title-block-banner-color: black
    theme: cosmo
    css: styles.css





